USE calendar;

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(50) UNIQUE,
  name VARCHAR(30) NOT NULL ,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE plans(
    plan_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    plan VARCHAR(10000)
);

ALTER TABLE plans
ADD COLUMN write_date DATETIME;

ALTER TABLE users
ADD COLUMN  email VARCHAR(100);

